### ISSUE TITLE
fileManager.blade.php problems. 

### ISSUE THREAD

**Issue by benzeety** [SWEET1S/moonshine-filemanager#2]
Проблема в fileManager.blade.php, не может найти document.querySelector('.lfm_{{ $uniqueID }}'), так как там уже используется .lfm**__**{{ $uniqueID }}, как и во всем остальном файле.
```
lfmInput{{ $uniqueID }}.addEventListener('change', function () {
        let values = lfmInput{{ $uniqueID }}.value.split(',');

        let newValues = new Set(initialValues_{{ $uniqueID }}.concat(values));

        lfmInput{{ $uniqueID }}.value = Array.from(newValues).join(',') || null;

        document.querySelector('.lfm_{{ $uniqueID }}').innerText = `{{ $element->getTitle() }} (${newValues.size})`
    });
```

Также есть с <x-moonshine::form.file-item> которая требует itemAttributes для своей работы.

Это из тех ошибок, которые я смог сам найти, остальное работает, но моментами странно, у dropzone стоит x-data="sortable", но при этом вся сортировка затирается при сохранении, так как главный input не меняется в ходе сортировки. Также у меня не выводится прикреплённая картинка сразу в dropzone, число на кнопке меняется, а вот новый item не добавляется.

**Comment by muhammadrafihq** [comment]
i custom my blade to like this,
maybe you want to try

`@use('Sweet1s\MoonshineFileManager\FileManagerTypeEnum')

@php
$uniqueId = uniqid();
@endphp

<x-moonshine::form.input
    type="hidden"
    id="lfm-input-{{ $uniqueId }}"
    class="lfm-input-{{ $uniqueId }}"
    :name="$element->name()"
    :value="implode(',', $element->getFullPathValues())"
/>

<div class="form-group form-group-dropzone">
    <x-moonshine::form.button
        data-input="lfm-input-{{ $uniqueId }}"
        class="lfm-{{ $uniqueId }}"
    >
        {{ $element->getTitle() }}
    </x-moonshine::form.button>
    
    @if($element->isMultiple())
        <p>* allow multiple</p>
    @else
        <p>* disallow multiple</p>
    @endif

    @php($raw = is_iterable($value) ? $value : [$value])
    @php($files = $element->getFullPathValues())

    @if(is_array($files) ? array_filter($files) : $files->isNotEmpty())
        <div class="dropzone">
            <div class="dropzone-items"
                 x-data="sortable"
                 data-handle=".dropzone-item"
            >
                @foreach($files as $index => $file)
                    <x-moonshine::form.file-item
                        :attributes="$element->attributes()->merge([
                            'id' => $element->id(),
                            'name' => $element->name()
                        ])"
                        :raw="$raw[$index]"
                        :file="$file"
                        :download="$element->getTypeOfFileManager() === FileManagerTypeEnum::Image ? false : $element->canDownload()"
                        :removable="$element->isRemovable()"
                        :removableAttributes="$element->getRemovableAttributes()"
                        :imageable="$element->getTypeOfFileManager() === FileManagerTypeEnum::Image"
                    />
                @endforeach
            </div>
        </div>
    @endif
</div>

<script>
    let lfm{{ $uniqueId }} = function (id, options) {
        let buttons = document.querySelectorAll(`.${id}`);

        buttons.forEach((button) => {
            button.addEventListener('click', function () {
                let route_prefix = (options && options.prefix) ? options.prefix : '/filemanager';
                let target_input = document.getElementById(button.getAttribute('data-input'));

                window.open(route_prefix , 'FileManager', 'width=900,height=600');
                window.SetUrl = function (items) {
                    let file_path = items.map(function (item) {
                        return item.url;
                    }).join(',');

                    target_input.value = file_path;
                    target_input.dispatchEvent(new Event('change'));

                    items.forEach(function (item) {
                        let img = document.createElement('img')
                        img.setAttribute('style', 'height: 5rem')
                        img.setAttribute('src', item.thumb_url)
                    });
                };
            });
        });
    };

    let route_prefix{{ $uniqueId }} = "{{ url('filemanager') }}";
    lfm{{ $uniqueId }}('lfm-{{ $uniqueId }}', {prefix: route_prefix{{ $uniqueId }}});

    let lfmInput{{ $uniqueId }} = document.querySelector('.lfm-input-{{ $uniqueId }}');

    let initialValues{{ $uniqueId }} = JSON.parse('{!! json_encode($element->getFullPathValues()) !!}');

    document.querySelectorAll('.lfm-{{ $uniqueId }} + * button').forEach((button) => {
        button.addEventListener('click', function () {
            let image = button.nextElementSibling.getAttribute('src');

            let values = lfmInput{{ $uniqueId }}.value.split(',');

            if (values.includes(image)) {
                values = values.filter(function (value) {
                    return value !== image;
                });
            } else {
                values.push(image);
            }

            lfmInput{{ $uniqueId }}.value = values.join(',');
        });
    });

    lfmInput{{ $uniqueId }}.addEventListener('change', function () {
    let values = lfmInput{{ $uniqueId }}.value.split(',');

    if (values.length > 1 && !{!! json_encode($element->isMultiple()) !!}) {
    alert('Please select only one file.');
    lfmInput{{ $uniqueId }}.value = ''; 
}
else {
        let newValues = new Set(initialValues{{ $uniqueId }}.concat(values));

        lfmInput{{ $uniqueId }}.value = Array.from(newValues).join(',') || null;

        document.querySelector('.lfm-{{ $uniqueId }}').innerText = `{{ $element->getTitle() }} (${newValues.size})`;
    }
});

</script>
`

**Comment by muhammadrafihq** [comment]
i custom my blade to like this,
maybe you want to try.

i adding so can multiple or not
```

@use('Sweet1s\MoonshineFileManager\FileManagerTypeEnum')

@php
$uniqueId = uniqid();
@endphp

<x-moonshine::form.input
    type="hidden"
    id="lfm-input-{{ $uniqueId }}"
    class="lfm-input-{{ $uniqueId }}"
    :name="$element->name()"
    :value="implode(',', $element->getFullPathValues())"
/>

<div class="form-group form-group-dropzone">
    <x-moonshine::form.button
        data-input="lfm-input-{{ $uniqueId }}"
        class="lfm-{{ $uniqueId }}"
    >
        {{ $element->getTitle() }}
    </x-moonshine::form.button>
    
    @if($element->isMultiple())
        <p>* allow multiple</p>
    @else
        <p>* disallow multiple</p>
    @endif

    @php($raw = is_iterable($value) ? $value : [$value])
    @php($files = $element->getFullPathValues())

    @if(is_array($files) ? array_filter($files) : $files->isNotEmpty())
        <div class="dropzone">
            <div class="dropzone-items"
                 x-data="sortable"
                 data-handle=".dropzone-item"
            >
                @foreach($files as $index => $file)
                    <x-moonshine::form.file-item
                        :attributes="$element->attributes()->merge([
                            'id' => $element->id(),
                            'name' => $element->name()
                        ])"
                        :raw="$raw[$index]"
                        :file="$file"
                        :download="$element->getTypeOfFileManager() === FileManagerTypeEnum::Image ? false : $element->canDownload()"
                        :removable="$element->isRemovable()"
                        :removableAttributes="$element->getRemovableAttributes()"
                        :imageable="$element->getTypeOfFileManager() === FileManagerTypeEnum::Image"
                    />
                @endforeach
            </div>
        </div>
    @endif
</div>

<script>
    let lfm{{ $uniqueId }} = function (id, options) {
        let buttons = document.querySelectorAll(`.${id}`);

        buttons.forEach((button) => {
            button.addEventListener('click', function () {
                let route_prefix = (options && options.prefix) ? options.prefix : '/filemanager';
                let target_input = document.getElementById(button.getAttribute('data-input'));

                window.open(route_prefix , 'FileManager', 'width=900,height=600');
                window.SetUrl = function (items) {
                    let file_path = items.map(function (item) {
                        return item.url;
                    }).join(',');

                    target_input.value = file_path;
                    target_input.dispatchEvent(new Event('change'));

                    items.forEach(function (item) {
                        let img = document.createElement('img')
                        img.setAttribute('style', 'height: 5rem')
                        img.setAttribute('src', item.thumb_url)
                    });
                };
            });
        });
    };

    let route_prefix{{ $uniqueId }} = "{{ url('filemanager') }}";
    lfm{{ $uniqueId }}('lfm-{{ $uniqueId }}', {prefix: route_prefix{{ $uniqueId }}});

    let lfmInput{{ $uniqueId }} = document.querySelector('.lfm-input-{{ $uniqueId }}');

    let initialValues{{ $uniqueId }} = JSON.parse('{!! json_encode($element->getFullPathValues()) !!}');

    document.querySelectorAll('.lfm-{{ $uniqueId }} + * button').forEach((button) => {
        button.addEventListener('click', function () {
            let image = button.nextElementSibling.getAttribute('src');

            let values = lfmInput{{ $uniqueId }}.value.split(',');

            if (values.includes(image)) {
                values = values.filter(function (value) {
                    return value !== image;
                });
            } else {
                values.push(image);
            }

            lfmInput{{ $uniqueId }}.value = values.join(',');
        });
    });

    lfmInput{{ $uniqueId }}.addEventListener('change', function () {
    let values = lfmInput{{ $uniqueId }}.value.split(',');

    if (values.length > 1 && !{!! json_encode($element->isMultiple()) !!}) {
    alert('Please select only one file.');
    lfmInput{{ $uniqueId }}.value = ''; 
}
else {
        let newValues = new Set(initialValues{{ $uniqueId }}.concat(values));

        lfmInput{{ $uniqueId }}.value = Array.from(newValues).join(',') || null;

        document.querySelector('.lfm-{{ $uniqueId }}').innerText = `{{ $element->getTitle() }} (${newValues.size})`;
    }
});

</script>

```

**Comment by benzeety** [comment]
It's not work for me, get error with itemAttributes required param.

> i custom my blade to like this, maybe you want to try.
> 
> i adding so can multiple or not
> 
> ```
> 
> @use('Sweet1s\MoonshineFileManager\FileManagerTypeEnum')
> 
> @php
> $uniqueId = uniqid();
> @endphp
> 
> <x-moonshine::form.input
>     type="hidden"
>     id="lfm-input-{{ $uniqueId }}"
>     class="lfm-input-{{ $uniqueId }}"
>     :name="$element->name()"
>     :value="implode(',', $element->getFullPathValues())"
> />
> 
> <div class="form-group form-group-dropzone">
>     <x-moonshine::form.button
>         data-input="lfm-input-{{ $uniqueId }}"
>         class="lfm-{{ $uniqueId }}"
>     >
>         {{ $element->getTitle() }}
>     </x-moonshine::form.button>
>     
>     @if($element->isMultiple())
>         <p>* allow multiple</p>
>     @else
>         <p>* disallow multiple</p>
>     @endif
> 
>     @php($raw = is_iterable($value) ? $value : [$value])
>     @php($files = $element->getFullPathValues())
> 
>     @if(is_array($files) ? array_filter($files) : $files->isNotEmpty())
>         <div class="dropzone">
>             <div class="dropzone-items"
>                  x-data="sortable"
>                  data-handle=".dropzone-item"
>             >
>                 @foreach($files as $index => $file)
>                     <x-moonshine::form.file-item
>                         :attributes="$element->attributes()->merge([
>                             'id' => $element->id(),
>                             'name' => $element->name()
>                         ])"
>                         :raw="$raw[$index]"
>                         :file="$file"
>                         :download="$element->getTypeOfFileManager() === FileManagerTypeEnum::Image ? false : $element->canDownload()"
>                         :removable="$element->isRemovable()"
>                         :removableAttributes="$element->getRemovableAttributes()"
>                         :imageable="$element->getTypeOfFileManager() === FileManagerTypeEnum::Image"
>                     />
>                 @endforeach
>             </div>
>         </div>
>     @endif
> </div>
> 
> <script>
>     let lfm{{ $uniqueId }} = function (id, options) {
>         let buttons = document.querySelectorAll(`.${id}`);
> 
>         buttons.forEach((button) => {
>             button.addEventListener('click', function () {
>                 let route_prefix = (options && options.prefix) ? options.prefix : '/filemanager';
>                 let target_input = document.getElementById(button.getAttribute('data-input'));
> 
>                 window.open(route_prefix , 'FileManager', 'width=900,height=600');
>                 window.SetUrl = function (items) {
>                     let file_path = items.map(function (item) {
>                         return item.url;
>                     }).join(',');
> 
>                     target_input.value = file_path;
>                     target_input.dispatchEvent(new Event('change'));
> 
>                     items.forEach(function (item) {
>                         let img = document.createElement('img')
>                         img.setAttribute('style', 'height: 5rem')
>                         img.setAttribute('src', item.thumb_url)
>                     });
>                 };
>             });
>         });
>     };
> 
>     let route_prefix{{ $uniqueId }} = "{{ url('filemanager') }}";
>     lfm{{ $uniqueId }}('lfm-{{ $uniqueId }}', {prefix: route_prefix{{ $uniqueId }}});
> 
>     let lfmInput{{ $uniqueId }} = document.querySelector('.lfm-input-{{ $uniqueId }}');
> 
>     let initialValues{{ $uniqueId }} = JSON.parse('{!! json_encode($element->getFullPathValues()) !!}');
> 
>     document.querySelectorAll('.lfm-{{ $uniqueId }} + * button').forEach((button) => {
>         button.addEventListener('click', function () {
>             let image = button.nextElementSibling.getAttribute('src');
> 
>             let values = lfmInput{{ $uniqueId }}.value.split(',');
> 
>             if (values.includes(image)) {
>                 values = values.filter(function (value) {
>                     return value !== image;
>                 });
>             } else {
>                 values.push(image);
>             }
> 
>             lfmInput{{ $uniqueId }}.value = values.join(',');
>         });
>     });
> 
>     lfmInput{{ $uniqueId }}.addEventListener('change', function () {
>     let values = lfmInput{{ $uniqueId }}.value.split(',');
> 
>     if (values.length > 1 && !{!! json_encode($element->isMultiple()) !!}) {
>     alert('Please select only one file.');
>     lfmInput{{ $uniqueId }}.value = ''; 
> }
> else {
>         let newValues = new Set(initialValues{{ $uniqueId }}.concat(values));
> 
>         lfmInput{{ $uniqueId }}.value = Array.from(newValues).join(',') || null;
> 
>         document.querySelector('.lfm-{{ $uniqueId }}').innerText = `{{ $element->getTitle() }} (${newValues.size})`;
>     }
> });
> 
> </script>
> ```

**Comment by SWEET1S** [comment]
Добрый день. Я внес изменения в файл BLADE, чтобы исправить эти ошибки. Пожалуйста, обновите пакет до последней версии. Прошу прощения, что так долго, я был очень занят на работе и наконец-то дошли руки.

> It's not work for me, get error with itemAttributes required param.
> 
> > i custom my blade to like this, maybe you want to try.
> > i adding so can multiple or not
> > ```
> > 
> > @use('Sweet1s\MoonshineFileManager\FileManagerTypeEnum')
> > 
> > @php
> > $uniqueId = uniqid();
> > @endphp
> > 
> > <x-moonshine::form.input
> >     type="hidden"
> >     id="lfm-input-{{ $uniqueId }}"
> >     class="lfm-input-{{ $uniqueId }}"
> >     :name="$element->name()"
> >     :value="implode(',', $element->getFullPathValues())"
> > />
> > 
> > <div class="form-group form-group-dropzone">
> >     <x-moonshine::form.button
> >         data-input="lfm-input-{{ $uniqueId }}"
> >         class="lfm-{{ $uniqueId }}"
> >     >
> >         {{ $element->getTitle() }}
> >     </x-moonshine::form.button>
> >     
> >     @if($element->isMultiple())
> >         <p>* allow multiple</p>
> >     @else
> >         <p>* disallow multiple</p>
> >     @endif
> > 
> >     @php($raw = is_iterable($value) ? $value : [$value])
> >     @php($files = $element->getFullPathValues())
> > 
> >     @if(is_array($files) ? array_filter($files) : $files->isNotEmpty())
> >         <div class="dropzone">
> >             <div class="dropzone-items"
> >                  x-data="sortable"
> >                  data-handle=".dropzone-item"
> >             >
> >                 @foreach($files as $index => $file)
> >                     <x-moonshine::form.file-item
> >                         :attributes="$element->attributes()->merge([
> >                             'id' => $element->id(),
> >                             'name' => $element->name()
> >                         ])"
> >                         :raw="$raw[$index]"
> >                         :file="$file"
> >                         :download="$element->getTypeOfFileManager() === FileManagerTypeEnum::Image ? false : $element->canDownload()"
> >                         :removable="$element->isRemovable()"
> >                         :removableAttributes="$element->getRemovableAttributes()"
> >                         :imageable="$element->getTypeOfFileManager() === FileManagerTypeEnum::Image"
> >                     />
> >                 @endforeach
> >             </div>
> >         </div>
> >     @endif
> > </div>
> > 
> > <script>
> >     let lfm{{ $uniqueId }} = function (id, options) {
> >         let buttons = document.querySelectorAll(`.${id}`);
> > 
> >         buttons.forEach((button) => {
> >             button.addEventListener('click', function () {
> >                 let route_prefix = (options && options.prefix) ? options.prefix : '/filemanager';
> >                 let target_input = document.getElementById(button.getAttribute('data-input'));
> > 
> >                 window.open(route_prefix , 'FileManager', 'width=900,height=600');
> >                 window.SetUrl = function (items) {
> >                     let file_path = items.map(function (item) {
> >                         return item.url;
> >                     }).join(',');
> > 
> >                     target_input.value = file_path;
> >                     target_input.dispatchEvent(new Event('change'));
> > 
> >                     items.forEach(function (item) {
> >                         let img = document.createElement('img')
> >                         img.setAttribute('style', 'height: 5rem')
> >                         img.setAttribute('src', item.thumb_url)
> >                     });
> >                 };
> >             });
> >         });
> >     };
> > 
> >     let route_prefix{{ $uniqueId }} = "{{ url('filemanager') }}";
> >     lfm{{ $uniqueId }}('lfm-{{ $uniqueId }}', {prefix: route_prefix{{ $uniqueId }}});
> > 
> >     let lfmInput{{ $uniqueId }} = document.querySelector('.lfm-input-{{ $uniqueId }}');
> > 
> >     let initialValues{{ $uniqueId }} = JSON.parse('{!! json_encode($element->getFullPathValues()) !!}');
> > 
> >     document.querySelectorAll('.lfm-{{ $uniqueId }} + * button').forEach((button) => {
> >         button.addEventListener('click', function () {
> >             let image = button.nextElementSibling.getAttribute('src');
> > 
> >             let values = lfmInput{{ $uniqueId }}.value.split(',');
> > 
> >             if (values.includes(image)) {
> >                 values = values.filter(function (value) {
> >                     return value !== image;
> >                 });
> >             } else {
> >                 values.push(image);
> >             }
> > 
> >             lfmInput{{ $uniqueId }}.value = values.join(',');
> >         });
> >     });
> > 
> >     lfmInput{{ $uniqueId }}.addEventListener('change', function () {
> >     let values = lfmInput{{ $uniqueId }}.value.split(',');
> > 
> >     if (values.length > 1 && !{!! json_encode($element->isMultiple()) !!}) {
> >     alert('Please select only one file.');
> >     lfmInput{{ $uniqueId }}.value = ''; 
> > }
> > else {
> >         let newValues = new Set(initialValues{{ $uniqueId }}.concat(values));
> > 
> >         lfmInput{{ $uniqueId }}.value = Array.from(newValues).join(',') || null;
> > 
> >         document.querySelector('.lfm-{{ $uniqueId }}').innerText = `{{ $element->getTitle() }} (${newValues.size})`;
> >     }
> > });
> > 
> > </script>
> > ```

**Comment by SWEET1S** [comment]
Добрый день. Я внес изменения в файл BLADE, чтобы исправить эти ошибки. Пожалуйста, обновите пакет до последней версии. Прошу прощения, что так долго, я был очень занят на работе и наконец-то дошли руки.

----

Good afternoon. I have made changes to the BLADE file to fix these errors. Please update the package to the latest version. I apologize for taking so long, I've been very busy at work and finally got to my hands.

**Comment by SWEET1S** [comment]
@muhammadrafihq 

The changes you've made are unnecessary. By default the file manager is Multiple, and unfortunately it cannot be changed. If you succeeded, I'm waiting for Pull Request
